---
name: SNMP-Class
version: 0.05
author:
  - 'Athanasios Douitsis <aduitsis@cpan.org>'
abstract: A convenience class around the NetSNMP perl modules.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Std: 0
  Log::Log4perl: 0
  NetSNMP::OID: 0
  SNMP: 0
build_requires:
  Test::More: 0
provides:
  SNMP::Class:
    file: lib/SNMP/Class.pm
    version: 0.05
  SNMP::Class::OID:
    file: lib/SNMP/Class/OID.pm
    version: 0.01
  SNMP::Class::ResultSet:
    file: lib/SNMP/Class/ResultSet.pm
    version: 0.01
  SNMP::Class::Utils:
    file: lib/SNMP/Class/Utils.pm
  SNMP::Class::Varbind:
    file: lib/SNMP/Class/Varbind.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
